### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xtmgah** [dnieuw/IGVshiny#1]
Hello:

Very very great app to load the used bam files and show the IGVs. I try to test it but when i load a bam and bam files, there are always show error information about "Error accessing resource 404". 

I think the bam files loaded was not accessible by IGVjs. Do you have any idea to fix this? Thanks.

**Comment by dnieuw** [comment]
Yeah, there is a problem with loading BAM files. I have discontinued working on the implementation of IGVjs in shiny because shiny-server does not provide byte serving functionallity, which is needed to load partial chunks of the BAM file. So unless that is enabled in shiny-server there is no way to get this custom IGVjs shiny widget working...

**Comment by xtmgah** [comment]
Thanks. I got it.
